fix: remove unnecessary span tags
vuejs-translations/docs-ru pull request #379
Opened 2024-03-26 17:57 UTC by Hekikai

## Description of Problem
Проблема с тегами - из-за них не отображался текст из-за стилей
## Proposed Solution
Убран ненужный класс
## Additional Information
resolves #375

2024-04-03 10:21 UTC, dragomano commented
Смысл этих классов в отображении различного текста в зависимости от выбранного стиля API - Composition API или Options API. Посмотрите английскую версию документации.

2024-04-03 10:36 UTC, Ibochkarev commented
@Hekikai удалять ничего не нужно - у нас проблема с переводом https://github.com/vuejs/docs/blob/main/src/guide/essentials/template-refs.md?plain=1#L217

В оригинале одно слово только выделяется `<span class="options-api">The</span>`

2024-04-03 10:37 UTC, Ibochkarev requested changes
оставил коммент

2024-04-03 15:56 UTC, Hekikai commented
@Ibochkarev @dragomano понял, спасибо, поправлю!

2024-04-04 16:24 UTC, Ibochkarev approved these changes
Теперь все ок!

2024-04-04 16:24 UTC, merged