translate: parts in /guide/components, fix: errors
vuejs-translations/docs-ru pull request #415
Opened 2024-04-24 20:46 UTC by mnenie

## Description of Problem

Были недопереведены некоторые участки в /guide/components
Небольшие ошибки в переводе.

## Proposed Solution

Переведены участки в блоках  /guide/components
Исправлены ошибки

2024-04-27 14:07 UTC, Ibochkarev requested changes

2024-04-27 14:07 UTC, Ibochkarev commented on src/guide/components/v-model.md
> +:::Предупреждение
Оставить как было и через пробел русский перевод

2024-04-27 14:18 UTC, mnenie commented on src/guide/components/v-model.md
> +:::Предупреждение
Сделано

2024-05-02 22:12 UTC, mnenie commented
@Ibochkarev проверьте, пожалуйста, вроде все исправил.

2024-05-04 05:42 UTC, Ibochkarev approved these changes

2024-05-04 05:42 UTC, merged